# Autostart applications

exec-once = /usr/lib/polkit-kde-authentication-agent-1
exec-once = mako
exec-once = waybar
exec-once = nm-applet --indicator
exec-once = swaybg -i /home/geissinger/Pictures/Wallpaper/2186eb64-13a7-484c-bd4c-99ef0c9cbe12.png -m fill

#exec-once = hyprpaper
#exec-once = awww-daemon
#exec-once = awww img /home/geissinger/Pictures/Wallpaper/2186eb64-13a7-484c-bd4c-99ef0c9cbe12.png


# Clipboard history
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
