background {
    monitor =
    color = rgba(1e1e2eff)
}

input-field {
    monitor =
    size = 300, 60
    position = 0, -20
    halign = center
    valign = center

    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.2

    outer_color = rgba(89b4faee)
    inner_color = rgba(1e1e2eff)
    font_color = rgba(cdd6f4ff)
    placeholder_text = Passwort...
}
