# Window rules

# Useful floating dialogs
windowrule = match:class pavucontrol, float on
windowrule = match:class blueman-manager, float on
windowrule = match:title Open File, float on
windowrule = match:title Save File, float on
windowrule = match:title Authentication Required, float on

# Picture-in-picture
windowrule = match:title Picture-in-Picture, float on
windowrule = match:title Picture-in-Picture, pin on
windowrule = match:title Picture-in-Picture, size 30% 30%
windowrule = match:title Picture-in-Picture, move 69% 5%
