# Window rules

# Useful floating dialogs
windowrulev2 = float,class:^(pavucontrol)$
windowrulev2 = float,class:^(blueman-manager)$
windowrulev2 = float,title:^(Open File)$
windowrulev2 = float,title:^(Save File)$
windowrulev2 = float,title:^(Authentication Required)$

# Picture-in-picture
windowrulev2 = float,title:^(Picture-in-Picture)$
windowrulev2 = pin,title:^(Picture-in-Picture)$
windowrulev2 = size 30% 30%,title:^(Picture-in-Picture)$
windowrulev2 = move 69% 5%,title:^(Picture-in-Picture)$
