# Autostart applications

exec-once = /usr/lib/polkit-kde-authentication-agent-1
exec-once = mako
exec-once = waybar
exec-once = nm-applet --indicator
exec-once = awww-daemon
exec-once = sleep 2 && /home/nerdnarok/.config/hypr/scripts/wallpaper-daemon.sh
#exec-once = awww img /home/nerdnarok/Bilder/Wallpapers/wallpaper.jpg --transition-type grow --transition-duration 1
#exec-once = hyprpaper


# Clipboard history
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
